In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline
import random

In [4]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [5]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print (arr2.ndim) # Counts the number of subarrays
print (arr2.shape) # matrix shape
print (arr2.dtype) # type of elements in the array

2
(2, 4)
int32


In [7]:
print ('Creating an array with 0s as elements')
np.zeros(8)

Creating an array with 0s as elements


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [9]:
print ('It creates an array 1s as elements')
np.ones((2,3)) 

It creates an array 1s as elements


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
print ('It creates the identity matrix , size should be provided')
np.eye(3) 

It creates the identity matrix , size should be provided


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [19]:
arr3 = np.array([1.1,2.2,3.3,4.4])

In [20]:
print ('It changes from floating to integer by truncating the number')
arr3.astype(np.int32) 

It changes from floating to integer by truncating the number


array([1, 2, 3, 4])

In [22]:
print ('It retrieves an specific element in the array')
print (arr3[2])
print ('Note: the astype method does not change the actual value of the elements, it just truncates the number')

It retrieves an specific element in the array
3.3
Note: the astype method does not change the actual value of the elements, it just truncates the number


## Arrays Manipulation
----------------------------------------------

In [ ]:
arr4 = np.arange(10)
arr4

In [ ]:
print 'It changes the values of specific positions in the array'
arr4[6:8] = 12 
print (arr4)
print ('Note: in mathematical terms (6:8], 6 exclusive & 8 inclusive')

In [ ]:
arr_slice = arr4[6:8]

In [ ]:
print 'Changes in this array will affect the values of the original array too'
arr_slice[1] = 12345 
print (arr_slice)
print ('Note: keep in mind that by using [1], it is only modifying one element of the subarray')

In [ ]:
arr4

In [ ]:
arr_slice[:] = 64 # Changes will affect the source

In [ ]:
arr4

In [ ]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Finding elements in the array
print ('Full Array')
print (arr5)
print ('Sub Array')
print (arr5[2])
print ('Single Element')
print (arr5[2][2])

### Array notation

To retrieve elements you can use [:]

        * [x:] : Tells numpy to take the elements AFTER x so it won't include x
        * [:y] : Tells numpy to take the elments BEFORE y so it won't include y

In [ ]:
arr5[:2]

In [ ]:
print ('Here the filtering is at arrays level')
print (arr5[:2][1:] )
print ('Note: the array positions start from 1 not from 0')

In [ ]:
print ('Here the 1st filter is array level, the 2nd filters the elements of the arrays selected')
arr5[:2, 1:] 

In [ ]:
print ('This will basicalle take the first subelement of all the first level elements')
print (arr5[:,:1] )
print (arr5[:,0] )
print ('Note: The position for elements inside an array starts from 0 not 1')

In [ ]:
# How to look for matching values in 2 arrays
# in1d returns boolean results if any of the values are in the target array

values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

In [ ]:
data1 = np.random.randn(7,4)
data1

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
# Boolean match for an specific value within an array

names == 'Bob'

In [ ]:
np.unique(names)

In [ ]:
data1[names == 'Bob'] 

If you look at the text array the 1st & 4th Elements are true while the rest are false.

The data1 array is 7 x 4 matrix, so the columns lenght match the number of elements in the names array.

Python will select the 1st & 4th Element on each column

In [ ]:
data1[names == 'Bob', 2:] # once applied the boolean logic I only pick the values from 2 column onwards

In [ ]:
data1[names == 'Bob', 3:][1] # further selection to pick one exact element

In [ ]:
data2 = np.random.randn(7,7)
data2

In [ ]:
data2[names == 'Bob'] 

The data2 array is a 7 x 7 Matrix so now Python will select the 1st & 4th elements by row

In [ ]:
mask = (names == 'Bob')|(names == 'Will') # the operator | means OR 
mask

In [ ]:
data1[(names == 'Bob')|(names == 'Will')] 
# It selects the 1st, 3rd, 4th & 5th element by column

### How to select elements from an Array & assign to them specific values

In [ ]:
data1[data1 <0] = 0
data1

In [ ]:
# The matching True values for one array 
# can be used to filter/match values on a different array
data1[names == 'Bob'] = 7 # When you found a value which is True you replace with a 7
data1

In [ ]:
arr6 = np.empty([8,4]) # It creates an empty array
arr6
# The array it is actually empty the values are not 0 altough the graphical representation seems like it

In [ ]:
# Fill an array by rows

for i in range(8):
    arr6[i] = i # what i am doing is assigning i to each of the elements in each row in the array
arr6

In [ ]:
arr6[[4,3,0,6]] # it selects the rows I am requesting

In [ ]:
arr6[[-3,-5,-7]] # it selects the rows but in this case starting from the bottom

In [ ]:
# Fill an array by columns

for i in range(4):
    arr6[:,i] = i # in this case I assigning the same value to the elements in the column instead of the row
arr6

In [ ]:
arr7 = np.arange(32).reshape(8,4) 
# It takes a sequence of values and converts them into a matrix
arr7

In [ ]:
# How to select an element in an array
print (arr7[1,0] )
print (arr7[1][0])

In [ ]:
print (arr7[[1,5,7,2], # this vector gives you the row position
     [0,3,1,2]]) # the vector gives you the column position

# It is equivalent to individually select:
print (arr7[1,0])
print (arr7[5,3])
print (arr7[7,1])
print (arr7[2,2])

### Select sub arrays and change the arrays order

In [ ]:
# The 1st vector picks rows and the 2nd one scramble the numbers on each row
arr7[[1,5,7,2]][:,[0,3,1,2]] 

In [ ]:
# same as previous but using a built in function
arr7[np.ix_([1,5,7,2], [0,3,1,2])] 

In [ ]:
arr8 = np.arange(15).reshape((3,5))
arr8

In [ ]:
arr8.T # The T method transposes the array, don't forget it is an array not a matrix

In [ ]:
arr9 = np.random.randn(6,3)
arr9

In [ ]:
np.dot(arr9.T, arr9) # Matrix multiplication

In [ ]:
arr10 = np.arange(16).reshape((2,2,4))
# Notation: (2,2,4)
# 2: number of vectors
# 2: number of rows
# 4: number of columns
arr10

In [ ]:
arr10.swapaxes(1,2) # it swaps the axis of the vectors

### Complex Arrays -- Structure arrays

In [ ]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

#### The dt array defines the type of field/data type for each element/pair on the s vector

In [ ]:
s['Name']

In [ ]:
s['Height'].mean()

In [ ]:
s[1]['Age']

### Numpy data manipulation

In [ ]:
# Outcome of data manipulation of a normal Python array
l = [ 0. ,  0.5,  1.5,  3. ,  5. ]
2 * l

In [ ]:
# Outcome of data manipulation of Numpy array
l = np.array(l)
print (l * 2)
print (l ** 2)

In [ ]:
g = np.linspace(5, 10, 15)
print (g)
print ('Parameters: Start, Stop, Number of data points between start and stop point')

### Basic Algebra

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [ ]:
a * b # element wise product

In [ ]:
np.dot(a,b) # Matrix multiplication

In [ ]:
np.inner(a,b) # Matrix similar

In [ ]:
o = np.outer(a,b) # It multiplies each element of vector b by each element of vector a
o

In [ ]:
np.linalg.matrix_power(o, 2)  # matrix power o ** 2

In [ ]:
np.linalg.eigvals(o)  # eigenvalues

In [ ]:
np.linalg.eig(o)  # eigenvalues + right eigenvectors

In [ ]:
np.linalg.norm(o, ord=1)  # norm of order 1

In [ ]:
np.linalg.norm(o, ord=2)  # norm of order 2 (default)

In [ ]:
np.linalg.norm(o, axis=0)  # along first axis

In [ ]:
np.linalg.norm(o, axis=1)  # along second axis

In [ ]:
arr11 = np.random.randn(5,4)
arr11

In [ ]:
print (arr11.mean()) # option 1
print (np.mean(arr11)) #option 2

In [ ]:
print (arr11.sum() )
print (np.sum(arr11))

In [ ]:
# ROWS Mean
arr11.mean(axis = 1)

In [ ]:
# COLUMNS Mean
arr11.mean(axis = 0)

In [ ]:
arr12 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr12

In [ ]:
print ('Cumulative Sum by column')
print (arr12.cumsum(0))
print ('Cumulative Sum by row')
print (arr12.cumsum(1))

In [ ]:
print ('Cumulative Product by column')
print (arr12.cumprod(0))
print ('Cumulative Product by row')
print (arr12.cumprod(1))

### Most common methods:
sum,
mean,
std, var,
min,max,
argmin, argmax,
cumsum,
cumprod,
exp,
sqrt

### Arrays comparison

In [ ]:
arrA = np.random.randn(8)
arrB = np.random.randn(8)

In [ ]:
np.maximum(arrA, arrB)

In [ ]:
arrA

In [ ]:
# Integer & Decimal components of a number

np.modf(arrA) # it breaks the number into the decimals and the integer components. Creates 2 different arrays

### How to create vectors and meshgrid

In [ ]:
points = np.arange(-1, 1, 0.01) # it creates a 1D vector

In [ ]:
xs,ys = np.meshgrid(points, points) # it creates a 2D vector combining the 1D


In [ ]:
xs

In [ ]:
ys

In [ ]:
arr13 = np.random.randn(100)
(arr13 > 0).sum() # It only sums those values greater than 0

In [ ]:
bools = np.array([False, False,True, False])

In [ ]:
bools.any() # True if at least one True value in the array

In [ ]:
bools.all() # True only all values are true in the array

In [ ]:
arr14 = np.random.rand(8)
arr14.sort()
arr14

In [ ]:
arr15 = np.random.randn(5,3)

In [ ]:
print ('Sort by rows')
arr15.sort(1)
print (arr15)
print ('Sort by columns')
arr15.sort(0)
print (arr15)

In [ ]:
# quick way to calculate the pencentile 5
large_arr = np.random.randn(1000)
large_arr.sort()
print (large_arr[int(0.05 * len(large_arr))] )
print (large_arr[50])

### Matrix operations

In [ ]:
x1 = np.random.randn(5,5)
mat = x1.T.dot(x1) # multipliying a matrix by its transpose

In [ ]:
from numpy.linalg import inv, qr

inv(mat) # it calculates the inverse of an specific matrix

In [ ]:
mat.dot(inv(mat))

In [ ]:
q,r = qr(mat) # it factorizes the matrix
r

### List of most common numpy linear algebra functions
[linear algebra](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html)

### List of most common random generation numbers functions
[Random generation functions](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.random.html)

### Use of If with Numpy ( Comparable to Excel If )

In [ ]:
arr17 = np.random.randn(4,4)
arr17

In [ ]:
np.where(arr17 > 0, 2, -2) # typical if where if condition is met do x if not do y

### Solving Systems of Linear Equations

We are going to solve equations of type:

$$
a \cdot x = b
$$

Consider the system of linear equations which fits the above type:

\begin{eqnarray}
a_1^1 \cdot x_1 + a_1^2 \cdot x_1 = b_1 \\
a_2^1 \cdot x_2 + a_2^2 \cdot x_2 = b_2
\end{eqnarray}

First, matrix $a$.

In [ ]:
a = np.array([[3, 1], [1, 2]])

Second, vector $b$.

In [ ]:
b = np.array([9, 8])

Third, the solution.

In [ ]:
x = np.linalg.solve(a, b)
x

In [ ]:
print (np.dot(a, x))  # checking
print ('Results matches vector b')

### Random Numbers

NumPy has powerful pseudo-random number generating functions available. Most of them get covered later. Very often, we use **standard-normally distributed pseudo-random numbers**.

In [ ]:
np.random.standard_normal()  # single number

In [ ]:
np.random.standard_normal(5)  # 1d array

In [ ]:
a = np.random.standard_normal((2, 6)) * 0.5  # 2d array
a

In [ ]:
np.round(a, 2)

### OLS Regression

NumPy provides two convenience functions to implement ordinary least squares regression. They are `np.polyfit` and `np.polyval`.

In [ ]:
a = 100 + 5 * np.random.standard_normal((2, 8))
a

In [ ]:
reg1 = np.polyfit(a[0],a[1],1) # Linear regression
reg1

In [ ]:
reg2 = np.polyfit(a[0],a[1],2) # Cuadratic regression
reg2

In [ ]:
reg3 = np.polyfit(a[0],a[1],3) # Cubic regression
reg3

Let us plot the regression lines

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(a[0], a[1], 'ro');
x = np.linspace(a[0].min(), a[0].max(), 100) # It creates 100 evenly distributed data points based on a[0] min to max
plt.plot(x, np.polyval(reg1, x), 'b--', label='linear') # polyval evaluates the regression result on each of the 100 data points
plt.plot(x, np.polyval(reg2, x), 'm-.', label='quadratic') # provided populating the results of each type of regression
plt.plot(x, np.polyval(reg3, x), 'g.', label='cubic')
plt.legend();

In [ ]:
reg8 = np.polyfit(a[0], a[1], 7)  # perfect regression
reg8

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(a[0], a[1], 'ro');
plt.plot(x, np.polyval(reg8, x), 'b', label='perfect')
plt.legend();

## Advance Numpy : Simulating Short Rate Processes

In this example, we are going to simulate the **Vasicek short rate model** using Python as well as NumPy and vectorization. The SDE of the model is given by:

$$
dr_t = \kappa(\theta - r_t)dt + \sigma dZ_t
$$

A possible discretization of the model is given by

$$
r_t = r_s + \kappa (\theta - r_s) \Delta t + \sigma \sqrt{\Delta t} z_t
$$

for $s = t - \Delta t$. $Z_t$ is a standard Brownian motion, $z$ a standard normally distributed rv.

In [ ]:
# All assumptions as Python variables

# model parameters
r0 = 0.01  # starting value
kappa = 1.0  # mean-reversion factor
theta = 0.025  # long-term mean
sigma = 0.01  # volatiltiy
T = 1.0  # time horizon in year fractions
# Monte Carlo parameters
I = 10  # number of paths
M = 15  # number of time intervals
dt = T / M  # length of time interval

### A Pure Python Version

Using import random

In [ ]:
def vasicek_python(I=I, M=M):
    paths = {}
    for i in xrange(I):
        path = [r0, ]
        for t in xrange(1, M + 1):
            r_t = path[t - 1] + kappa * (theta - path[t - 1]) * dt \
                    + sigma * dt ** 0.5 * random.gauss(0, 1)
            path.append(r_t)
        paths[i] = path
    return paths

### Breaking the Vasicek Simulation down

Let us start inside out:

    1. r_t: It calculates the interest rate value on each point
        a. It takes the result of the previous simulation as input --> t -1
        b. It uses the outcome of a normal distribution with mean 0 and standard deviation of 1 to add the 
            stochastic component
        c. The rest of the values are just parameters previously provided
        d. the result is appended to the path List
    2. Re run r_t to get the next value in the path
    3. Save all the values of the path in the paths dictionary
    4. Run again a full path repeating steps 1 to 4

In [ ]:
paths = vasicek_python(10,15)
%time paths = vasicek_python(10,15)

In [ ]:
plt.figure(figsize=(10, 6))
for i in paths.iterkeys():
    plt.plot(paths[i])

### The Vectorized NumPy Version

Let us run the same function but this time using Numpy vectorization

In [ ]:
np.random.standard_normal(2)

In [ ]:
def vasicek_numpy(I=I, M=M):
    paths = np.zeros((M + 1, I)) # matrix has M rows & I columns
    paths[0] = r0
    for t in xrange(1, M + 1):
        paths[t] = paths[t - 1] + kappa * (theta - paths[t - 1]) * dt \
                    + sigma * dt ** 0.5 * np.random.standard_normal(I)
    return paths

### Breaking down the simulation

Numpy uses vectors which offers the ability to run all the values of each step on 1

For 15 steps only 15 runs are needs which dramatically reduces processing time

In [ ]:
paths1 = vasicek_numpy(10,15)
%time paths1 = vasicek_numpy(10,15)

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(paths1);

### Individual Basic Functions

In [ ]:
x = [1,2,3]

In [ ]:
matrix = np.zeros((3 + 1, len(x)))
matrix[3, :] = x ** 3
matrix[2, :] = x ** 2
matrix[1, :] = x
matrix[0, :] = 1