### Numpy Primer
----------------------

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline
import random

### Arrays Manipulation
----------------------------------------------

In [2]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print ('It changes the values of specific positions in the array')
arr4[6:8] = 12 
print (arr4)
print ('Note: in mathematical terms (6:8], 6 exclusive & 8 inclusive')

It changes the values of specific positions in the array
[ 0  1  2  3  4  5 12 12  8  9]
Note: in mathematical terms (6:8], 6 exclusive & 8 inclusive


In [4]:
arr_slice = arr4[6:8]

In [5]:
print ('Changes in this array will affect the values of the original array too')
arr_slice[1] = 12345 
print (arr_slice)
print ('Note: keep in mind that by using [1], it is only modifying one element of the subarray')

Changes in this array will affect the values of the original array too
[   12 12345]
Note: keep in mind that by using [1], it is only modifying one element of the subarray


In [6]:
arr4

array([    0,     1,     2,     3,     4,     5,    12, 12345,     8,
           9])

In [7]:
arr_slice[:] = 64 # Changes will affect the source

In [8]:
arr4

array([ 0,  1,  2,  3,  4,  5, 64, 64,  8,  9])

In [9]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Finding elements in the array
print ('Full Array')
print (arr5)
print ('Sub Array')
print (arr5[2])
print ('Single Element')
print (arr5[2][2])

Full Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub Array
[7 8 9]
Single Element
9


### Array notation

To retrieve elements you can use [:]

        * [x:] : Tells numpy to take the elements AFTER x so it will include x
        * [:y] : Tells numpy to take the elments BEFORE y so it won't include y

In [10]:
arr5[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print ('Here the filtering is at arrays level')
print ('Note: the array positions start from 1 not from 0')
print (arr5[:2][1:] )

Here the filtering is at arrays level
Note: the array positions start from 1 not from 0
[[4 5 6]]


In [12]:
print ('Here the 1st filter is array level, the 2nd filters the elements of the arrays selected')
arr5[:2, 1:] 

Here the 1st filter is array level, the 2nd filters the elements of the arrays selected


array([[2, 3],
       [5, 6]])

In [13]:
print ('This will basicalle take the first subelement of all the first level elements')
print (arr5[:,:1] )
print (arr5[:,0] )

This will basicalle take the first subelement of all the first level elements
[[1]
 [4]
 [7]]
[1 4 7]


In [14]:
print('Searching for matching values between arrays')
print('in1d returns boolean results (True, False) if matching values are found')

values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

Searching for matching values between arrays
in1d returns boolean results (True, False) if matching values are found


array([ True, False, False,  True,  True, False,  True])

In [15]:
data1 = np.random.randn(7,4)
data1

array([[ 0.00558313,  1.72616804, -0.47341446, -1.14358375],
       [ 0.56061491, -0.11275766, -0.48563052, -0.4596297 ],
       [-0.21465064,  0.10772796,  2.78365934,  0.99170247],
       [-0.50588169,  0.4830533 , -0.41062352,  0.49042928],
       [-0.67434111, -0.14273455, -0.68503345, -0.34162872],
       [-1.24185182,  0.63360036, -1.04475162,  1.09843835],
       [ 0.84277111, -0.12438186,  0.32091235, -1.69102065]])

In [16]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [17]:
print('Searching for specific element within an array --> Boleean outcome')

names == 'Bob'

Searching for specific element within an array --> Boleean outcome


array([ True, False, False,  True, False, False, False])

In [18]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [19]:
data1[names == 'Bob'] 

array([[ 0.00558313,  1.72616804, -0.47341446, -1.14358375],
       [-0.50588169,  0.4830533 , -0.41062352,  0.49042928]])

If you look at the text array the 1st & 4th Elements are true while the rest are false.

The data1 array is 7 x 4 matrix, so the columns lenght match the number of elements in the names array.

Python will select the 1st & 4th Element on each column

In [20]:
data1[names == 'Bob', 2:] # once applied the boolean logic I only pick the values from 2 column onwards

array([[-0.47341446, -1.14358375],
       [-0.41062352,  0.49042928]])

In [21]:
data1[names == 'Bob', 3:][1] # further selection to pick one exact element

array([0.49042928])

In [22]:
data2 = np.random.randn(7,7)
data2

array([[-1.83619552e+00,  2.62020322e+00,  6.32679195e-01,
         6.97129463e-01,  4.91791601e-01,  1.22729255e+00,
         1.35662386e+00],
       [ 5.63366768e-01, -3.50100056e-04,  2.42120573e+00,
         4.40576166e-01, -7.98883770e-01,  5.49200512e-01,
         1.26601994e+00],
       [ 9.17614529e-01,  1.31889759e+00, -1.13519481e+00,
        -5.83733522e-01, -9.72846459e-01,  6.43431107e-01,
         7.14153076e-02],
       [-1.30783744e-01,  2.24041978e-01, -3.27907899e-01,
        -4.63760189e-01,  1.20788275e+00,  1.40731512e+00,
        -4.14729478e-01],
       [-5.71325488e-01, -1.04974076e+00,  4.42873319e-01,
         3.19669452e-01,  2.97864950e-03, -9.58264901e-01,
        -1.87358834e+00],
       [-8.21514846e-01,  6.47764995e-01,  1.37017584e-01,
         1.69735165e+00,  5.07859752e-02, -2.14917712e-02,
        -1.58076217e+00],
       [ 1.16232603e+00, -1.02697862e+00,  1.50346769e+00,
        -7.18317163e-03,  1.02317690e+00, -1.15967693e+00,
        -2.6535477

In [23]:
data2[names == 'Bob'] 

array([[-1.83619552,  2.62020322,  0.6326792 ,  0.69712946,  0.4917916 ,
         1.22729255,  1.35662386],
       [-0.13078374,  0.22404198, -0.3279079 , -0.46376019,  1.20788275,
         1.40731512, -0.41472948]])

The data2 array is a 7 x 7 Matrix so now Python will select the 1st & 4th elements by row

In [24]:
mask = (names == 'Bob')|(names == 'Will') # the operator | means OR 
mask

array([ True, False,  True,  True,  True, False, False])

In [25]:
data1[(names == 'Bob')|(names == 'Will')] 
# It selects the 1st, 3rd, 4th & 5th element by column

array([[ 0.00558313,  1.72616804, -0.47341446, -1.14358375],
       [-0.21465064,  0.10772796,  2.78365934,  0.99170247],
       [-0.50588169,  0.4830533 , -0.41062352,  0.49042928],
       [-0.67434111, -0.14273455, -0.68503345, -0.34162872]])

### How to select elements from an Array & assign specific values to them

In [26]:
data1[data1 <0] = 0
data1

array([[0.00558313, 1.72616804, 0.        , 0.        ],
       [0.56061491, 0.        , 0.        , 0.        ],
       [0.        , 0.10772796, 2.78365934, 0.99170247],
       [0.        , 0.4830533 , 0.        , 0.49042928],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.63360036, 0.        , 1.09843835],
       [0.84277111, 0.        , 0.32091235, 0.        ]])

In [27]:
# The matching True values for one array 
# can be used to filter/match values on a different array
data1[names == 'Bob'] = 7 # When you found a value which is True you replace with a 7
data1

array([[7.        , 7.        , 7.        , 7.        ],
       [0.56061491, 0.        , 0.        , 0.        ],
       [0.        , 0.10772796, 2.78365934, 0.99170247],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.63360036, 0.        , 1.09843835],
       [0.84277111, 0.        , 0.32091235, 0.        ]])

In [28]:
arr6 = np.empty([8,4]) # It creates an empty array
arr6
# The array it is actually empty the values are not 0 altough the graphical representation seems like it

array([[ 4.03808205e+202,  3.11271150e+207,  5.48445839e+202,
         2.01188999e+289],
       [-3.42738679e-294,  4.76493877e+202,  8.43573793e-304,
         7.13607504e+279],
       [ 5.99774817e+180,  1.39806877e-152,  2.58634777e+161,
         4.95267817e+223],
       [ 1.14484109e+243,  4.01760777e+242,  3.93545339e-310,
         1.20544719e+301],
       [ 1.05345486e-311,  1.75393304e-321,  2.17292369e-311,
         2.84381388e-308],
       [ 4.05069862e-249,  2.21717752e-301,  2.88020268e+002,
         2.09657710e-305],
       [ 1.13233957e-309,  2.88000000e+002,  1.36752682e-312,
         1.05067988e-304],
       [ 7.26303107e-297,  2.82767975e+097,  1.17568804e+214,
         5.80222660e+180]])

In [29]:
# Fill an array by rows

for i in range(8):
    arr6[i] = i # what i am doing is assigning i to each of the elements in each row in the array
arr6

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [30]:
arr6[[4,3,0,6]] # it selects the rows I am requesting

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [31]:
arr6[[-3,-5,-7]] # it selects the rows but in this case starting from the bottom

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [32]:
# Fill an array by columns

for i in range(4):
    arr6[:,i] = i # in this case I assigning the same value to the elements in the column instead of the row
arr6

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [33]:
arr7 = np.arange(32).reshape(8,4) 
# It takes a sequence of values and converts them into a matrix
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
# How to select an element in an array
print (arr7[1,0] )
print (arr7[1][0])

4
4


In [35]:
print (arr7[[1,5,7,2], # this vector gives you the row position
     [0,3,1,2]]) # the vector gives you the column position

# It is equivalent to individually select:
print (arr7[1,0])
print (arr7[5,3])
print (arr7[7,1])
print (arr7[2,2])

[ 4 23 29 10]
4
23
29
10


### Select sub arrays and change their order

In [36]:
# The 1st vector picks rows and the 2nd one scramble the numbers on each row
arr7[[1,5,7,2]][:,[0,3,1,2]] 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [37]:
# same as previous but using a built in function
arr7[np.ix_([1,5,7,2], [0,3,1,2])] 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [38]:
arr8 = np.arange(15).reshape((3,5))
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
arr8.T # The T method transposes the array, don't forget it is an array not a matrix

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [40]:
arr9 = np.random.randn(6,3)
arr9

array([[ 1.37967355, -1.39350555,  0.38400034],
       [ 0.73707738,  0.97012161,  1.70557009],
       [-0.52884934,  1.10293448, -0.28278835],
       [ 1.3494537 , -0.91483551,  0.98410998],
       [-0.50475021,  0.41358321,  1.13086559],
       [ 1.18905681,  0.06063326,  0.98881795]])

In [41]:
np.dot(arr9.T, arr9) # Matrix multiplication

array([[ 6.21611797, -3.16200222,  3.86945161],
       [-3.16200222,  5.11110961,  0.43497029],
       [ 3.86945161,  0.43497029,  6.36148522]])

In [42]:
arr10 = np.arange(16).reshape((2,2,4)) # This is a Tensor
# Notation: (2,2,4)
# 2: number of vectors
# 2: number of rows
# 4: number of columns
arr10

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
arr10.swapaxes(1,2) # it swaps the axis of the vectors

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])