## Arrays with Python Lists

Let us set the benchmark with pure Python. First, a vector as `list` object.

In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  # vector of numbers

Second, a matrix as list of list.

In [2]:
m = [v, v, v]  # matrix of numbers
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

Third a cube as nested list.

In [5]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  # cube of numbers
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [7]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [9]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## NumPy Data Structures

### Regular NumPy Arrays

NumPy is a cornerstone in the Python scientific stack and PyData ecosystem.

In [11]:
import numpy as np

It provides the powerful `ndarray` class for the handling of multi-dimensional arrays.

In [12]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [13]:
a[:2]  # indexing as with list objects in 1 dimension

array([0. , 0.5])

In [14]:
a.sum()  # sum of all elements

5.0

In [15]:
a.std()  # standard deviation

0.7071067811865476

In [16]:
a.cumsum()  # running cumulative sum

array([0. , 0.5, 1.5, 3. , 5. ])

Multiplication of a `list` object.

In [17]:
l = [ 0. ,  0.5,  1.5,  3. ,  5. ]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In contrast, vectorized operation on the array.

In [18]:
a * 2

array([0., 1., 2., 3., 4.])

In [19]:
a ** 2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

Universal functions for fast computations.

In [20]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [21]:
np.sqrt(2.5)

1.5811388300841898

In [22]:
import math

In [23]:
math.sqrt(2.5)

1.5811388300841898

In [24]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [25]:
b = np.array([a, a * 2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

Data selection via indexing.

In [26]:
b[0]  # first row

array([0. , 0.5, 1. , 1.5, 2. ])

In [27]:
b[0, 2]  # third element of first row

1.0

In [28]:
b.sum()

15.0

In [29]:
b.sum(axis=0)
  # sum along axis 0, i.e. column-wise sum

array([0. , 1.5, 3. , 4.5, 6. ])

In [30]:
b.sum(axis=1)
  # sum along axis 1, i.e. row-wise sum

array([ 5., 10.])

Typical construction of `ndarray` objects.

In [31]:
c = np.zeros((2, 3, 4), dtype='i', order='C')  # also: np.ones()
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [32]:
d = np.ones_like(c, dtype='f', order='C')  # also: np.zeros_like()
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [33]:
e = np.empty((2, 3, 4))
e

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.60218491e-306],
        [1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
         8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
         1.33510679e-306]],

       [[2.22522597e-306, 1.78019761e-306, 1.78019761e-306,
         1.20160711e-306],
        [1.78020169e-306, 1.42418172e-306, 2.04712906e-306,
         7.56589622e-307],
        [1.11258277e-307, 8.90111708e-307, 3.22643519e-307,
         9.79103798e-307]]])

In [34]:
f = np.empty_like(c)
f

array([[[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]],

       [[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]]], dtype=int32)

In [35]:
g = np.linspace(5, 10, 15)
g

array([ 5.        ,  5.35714286,  5.71428571,  6.07142857,  6.42857143,
        6.78571429,  7.14285714,  7.5       ,  7.85714286,  8.21428571,
        8.57142857,  8.92857143,  9.28571429,  9.64285714, 10.        ])

### Structured Arrays

In [36]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [37]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [38]:
s['Height'].mean()

1.7750001

In [39]:
s[1]['Age']

53

## Vectorization of Code

Two dummy data sets.

In [40]:
r = np.random.standard_normal((4, 3))
s = np.random.standard_normal((4, 3))

In [41]:
r

array([[ 1.43148387,  1.38037234,  0.64536013],
       [-0.8851537 ,  0.91642293, -3.50426386],
       [-0.82527852,  1.9241156 ,  0.1843527 ],
       [ 0.58993243, -0.06333645, -0.38488523]])

In [42]:
s

array([[ 0.29231247, -0.2522113 , -0.92149516],
       [-0.29380733,  0.57267565, -0.46562317],
       [-0.02814263, -0.10589288,  1.11183135],
       [ 0.52603298,  0.96593448, -0.39601049]])

Element-wise addition.

In [43]:
r + s

array([[ 1.72379634,  1.12816104, -0.27613503],
       [-1.17896103,  1.48909858, -3.96988703],
       [-0.85342115,  1.81822271,  1.29618405],
       [ 1.1159654 ,  0.90259804, -0.78089573]])

Broadcasting.

In [44]:
2 * r + 3

array([[ 5.86296773,  5.76074468,  4.29072026],
       [ 1.22969261,  4.83284587, -4.00852771],
       [ 1.34944296,  6.84823119,  3.3687054 ],
       [ 4.17986485,  2.87332711,  2.23022953]])

In [45]:
s

array([[ 0.29231247, -0.2522113 , -0.92149516],
       [-0.29380733,  0.57267565, -0.46562317],
       [-0.02814263, -0.10589288,  1.11183135],
       [ 0.52603298,  0.96593448, -0.39601049]])

In [46]:
s = np.random.standard_normal(3)
r + s

array([[ 1.01406327,  1.4779598 ,  1.00103703],
       [-1.3025743 ,  1.01401039, -3.14858696],
       [-1.24269912,  2.02170305,  0.5400296 ],
       [ 0.17251183,  0.03425101, -0.02920834]])

In [47]:
# causes intentional error
s = np.random.standard_normal(4)
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [ ]:
r.transpose() + s

In [ ]:
np.shape(r.T)

A general Python function.

In [ ]:
def f(x):
    return 3 * x + 5

In [ ]:
f(0.5)  # float object

In [ ]:
f(r)  # NumPy array

In [ ]:
# causes intentional error
import math
math.sin(r)

In [ ]:
np.sin(r)  # array as input

In [ ]:
np.sin(np.pi)  # float as input

## Memory Layout

Cf. http://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

In [ ]:
x = np.random.standard_normal((5, 100000))
y = 2 * x + 3  # linear equation y = a * x + b
C = np.array((x, y), order='C')
F = np.array((x, y), order='F')
x = 0.0; y = 0.0  # memory clean-up

In [ ]:
C[:2].round(2)

In [ ]:
%timeit C.sum()

In [ ]:
%timeit F.sum()

C ordering faster along second axis.

In [ ]:
%timeit C[0].sum(axis=0)

In [ ]:
%timeit C[0].sum(axis=1)

F ordering faster along first axis.

In [ ]:
%timeit F.sum(axis=0)

In [ ]:
%timeit F.sum(axis=1)

Absolute advantage for C ordering for operation along single axis.

In [ ]:
F = 0.0; C = 0.0  # memory clean-up

## Linear Algebra

### Basic Functionality

Let us start with two vectors (i.e. one-dimensional array objects).

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [ ]:
a * b  # element-wise product

In [ ]:
np.dot(a, b)  # dot product

In [ ]:
np.inner(a, b)  # inner product

In [ ]:
o = np.outer(a, b)  # outer product
o

In [ ]:
np.linalg.matrix_power(o, 2)  # matrix power o ** 2

In [ ]:
np.dot(o, o)  # same as before

In [ ]:
np.linalg.eigvals(o)  # eigenvalues

In [ ]:
np.linalg.eig(o)  # eigenvalues + right eigenvectors

In [ ]:
np.linalg.norm(o, ord=1)  # norm of order 1

In [ ]:
np.linalg.norm(o, ord=2)  # norm of order 2 (default)

In [ ]:
np.linalg.norm(o, axis=0)  # along first axis

In [ ]:
np.linalg.norm(o, axis=1)  # along second axis

In [ ]:
m = np.arange(4).reshape((2, 2))
m

In [ ]:
np.linalg.det(m)  # determinant

In [ ]:
i = np.linalg.inv(m)  # inverse
i

In [ ]:
np.dot(m, i)

In [ ]:
np.eye(2)

In [ ]:
np.dot(m, i) == np.eye(2)

### Soving Systems of Linear Equations

In [ ]:
import numpy as np

We are going to solve equations of type:

$$
a \cdot x = b
$$

Consider the system of linear equations which fits the above type:

\begin{eqnarray}
a_1^1 \cdot x_1 + a_1^2 \cdot x_1 = b_1 \\
a_2^1 \cdot x_2 + a_2^2 \cdot x_2 = b_2
\end{eqnarray}

First, matrix $a$.

In [ ]:
a = np.array([[3, 1], [1, 2]])

Second, vector $b$.

In [ ]:
b = np.array([9, 8])

Third, the solution.

In [ ]:
x = np.linalg.solve(a, b)
x

In [ ]:
np.dot(a, x)  # checking

Or larger matrices/vectors.

In [ ]:
a = np.array([[3, 1, 1], [1, 2, 1], [1, 1, 2]])

In [ ]:
b = np.array([10.5, 8.25, 7.75])

In [ ]:
x = np.linalg.solve(a, b)
x

In [ ]:
np.dot(a, x)  # checking

## Random Numbers

NumPy has powerful pseudo-random number generating functions available. Most of them get covered later. Very often, we use **standard-normally distributed pseudo-random numbers**.

In [ ]:
import numpy as np

In [ ]:
np.random.standard_normal()  # single number

In [ ]:
np.random.standard_normal(5)  # 1d array

In [ ]:
a = np.random.standard_normal((2, 6)) * 0.5  # 2d array
a

In [ ]:
np.round(a, 2)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(a[0], a[1], 'ro');

## OLS Regression 

NumPy provides two convenience functions to implement ordinary least squares regression. They are `np.polyfit` and `np.polyval`.

In [ ]:
a = 100 + 5 * np.random.standard_normal((2, 8))

In [ ]:
a = np.random.standard_normal((2, 8))

In [ ]:
reg1 = np.polyfit(a[0], a[1], 1)  # linear regression
reg1

In [ ]:
reg2 = np.polyfit(a[0], a[1], 2)  # quadratic regression
reg2

In [ ]:
reg3 = np.polyfit(a[0], a[1], 3)  # cubic regression
reg3

A plot of the regression lines.

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(a[0], a[1], 'ro');
x = np.linspace(a[0].min(), a[0].max(), 100)
plt.plot(x, np.polyval(reg1, x), 'b--', label='linear')
plt.plot(x, np.polyval(reg2, x), 'm-.', label='quadratic')
plt.plot(x, np.polyval(reg3, x), 'g.', label='cubic')
plt.legend();

A polynomial of degree 7 has 8 degrees of freedom.

In [ ]:
reg8 = np.polyfit(a[0], a[1], 7)  # perfect regression
reg8

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(a[0], a[1], 'ro');
plt.plot(x, np.polyval(reg8, x), 'b', label='perfect')
plt.legend();

## Simulating Short Rate Processes

In this example, we are going to simulate the **Vasicek short rate model** using Python as well as NumPy and vectorization. The SDE of the model is given by:

$$
dr_t = \kappa(\theta - r_t)dt + \sigma dZ_t
$$

A possible discretization of the model is given by

$$
r_t = r_s + \kappa (\theta - r_s) \Delta t + \sigma \sqrt{\Delta t} z_t
$$

for $s = t - \Delta t$. $Z_t$ is a standard Brownian motion, $z$ a standard normally distributed rv.

All assumptions as Python variables.

In [ ]:
# model parameters
r0 = 0.01  # starting value
kappa = 1.0  # mean-reversion factor
theta = 0.025  # long-term mean
sigma = 0.01  # volatiltiy
T = 1.0  # time horizon in year fractions
# Monte Carlo parameters
I = 10  # number of paths
M = 15  # number of time intervals
dt = T / M  # length of time interval

### A Pure Python Version

The Python function.

In [ ]:
import random

In [ ]:
def vasicek_python(I=I, M=M):
    paths = {}
    for i in xrange(I):
        path = [r0, ]
        for t in xrange(1, M + 1):
            r_t = path[t - 1] + kappa * (theta - path[t - 1]) * dt \
                    + sigma * dt ** 0.5 * random.gauss(0, 1)
            path.append(r_t)
        paths[i] = path
    return paths

The simulation and a sample path.

In [ ]:
%time paths  = vasicek_python()

In [ ]:
import cProfile

In [ ]:
func = '''
def vasicek_python(I=I, M=M):
    paths = {}
    for i in xrange(I):
        path = [r0, ]
        for t in xrange(1, M + 1):
            r_t = path[t - 1] + kappa * (theta - path[t - 1]) * dt \
                    + sigma * dt ** 0.5 * random.gauss(0, 1)
            path.append(r_t)
        paths[i] = path
    return paths
vasicek_python(I=10000, M=50)
'''

In [ ]:
cProfile.run(func)

In [ ]:
paths[0]

Some sample paths visualized. 

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline

In [ ]:
plt.figure(figsize=(10, 6))
for i in paths.iterkeys():
    plt.plot(paths[i])

### The Vectorized NumPy Version

A function using NumPy vectorization.

In [ ]:
def vasicek_numpy(I=I, M=M):
    paths = np.zeros((M + 1, I))
    paths[0] = r0
    for t in xrange(1, M + 1):
        paths[t] = paths[t - 1] + kappa * (theta - paths[t - 1]) * dt \
                    + sigma * dt ** 0.5 * np.random.standard_normal(I)
    return paths

In [ ]:
%time paths  = vasicek_numpy()

In [ ]:
func = '''
def vasicek_numpy(I=I, M=M):
    paths = np.zeros((M + 1, I))
    paths[0] = r0
    for t in xrange(1, M + 1):
        paths[t] = paths[t - 1] + kappa * (theta - paths[t - 1]) * dt \
                    + sigma * dt ** 0.5 * np.random.standard_normal(I)
    return paths
vasicek_numpy(I=10000, M=50)
'''

In [ ]:
cProfile.run(func)

The results object.

In [ ]:
paths

And a visualization of the results:

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(paths);

### Speed Comparison

We compare the speed of the pure Python version with that of the NumPy version on the basis of somewhat more meaningful parameters.

In [ ]:
I = 25000
M = 50

In [ ]:
%time paths_python = vasicek_python(I, M)

The speed-up of NumPy is more than 20.

In [ ]:
%time paths_numpy = vasicek_numpy(I, M)

### Dynamic Compiling

Now the application of dynamic compiling methods via Numba.

In [ ]:
import numba as nb

The hybrid function combines Python looping with NumPy `ndarray` objects (i.e. no vectorization).

In [ ]:
def vasicek_hybrid(I=I, M=M):
    paths = np.zeros((M + 1, I))
    paths[0] = r0
    for i in xrange(I):
        for t in xrange(1, M + 1):
            paths[t, i] = paths[t - 1, i - 1] + \
                kappa * (theta - paths[t - 1, i - 1]) * dt \
                + sigma * dt ** 0.5 * np.random.standard_normal()
    return paths

In [ ]:
%time paths_hybrid = vasicek_hybrid()

In [ ]:
vasicek_numba = nb.jit(vasicek_hybrid)

In [ ]:
%time paths_numba = vasicek_numba()  # first call involves overhead

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(paths_numba[:, :10]);

In [ ]:
%timeit vasicek_numba()

### Memory Layout

Finally, a somehow practical example for the importance of memory layouting.

In [ ]:
def vasicek_numpy_transpose(I=I, M=M):
    paths = np.zeros((I, M + 1))
    paths[0] = r0
    for t in xrange(1, M + 1):
        paths[:, t] = paths[:, t - 1] + kappa * (theta - paths[:, t - 1]) * dt \
                    + sigma * dt ** 0.5 * np.random.standard_normal(I)
    return paths

In [ ]:
I = 1000000
M = 10

In [ ]:
%time paths_numpy = vasicek_numpy(I, M)

In [ ]:
%time paths_numpy_transpose = vasicek_numpy_transpose(I, M)