### Numpy Primer
----------------------

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline
import random

### Matrix operations

In [2]:
x1 = np.random.randn(5,5)
mat = x1.T.dot(x1) # multipliying a matrix by its transpose

In [3]:
from numpy.linalg import inv, qr

inv(mat) # it calculates the inverse of an specific matrix

array([[ 0.4399249 ,  0.88717492, -0.71075278, -0.40433372, -0.37819493],
       [ 0.88717492,  4.56394669, -2.36388521, -2.92481441, -1.07505453],
       [-0.71075278, -2.36388521,  2.89151935,  1.3319921 ,  1.00517135],
       [-0.40433372, -2.92481441,  1.3319921 ,  2.77769755,  0.62113011],
       [-0.37819493, -1.07505453,  1.00517135,  0.62113011,  0.54631099]])

In [4]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.20338164e-15,  5.53608205e-16,
        -2.92443841e-16, -1.80992993e-16],
       [ 5.10243395e-17,  1.00000000e+00,  4.20783938e-16,
         4.92586147e-16,  1.76687088e-16],
       [ 1.49477169e-16, -1.40368662e-18,  1.00000000e+00,
        -4.18571046e-16, -3.97210601e-16],
       [ 1.12733545e-16,  2.15323418e-16, -3.79690921e-18,
         1.00000000e+00,  1.16075077e-16],
       [-5.47153431e-17, -8.15897106e-16,  9.56712752e-16,
         5.39162204e-16,  1.00000000e+00]])

In [5]:
q,r = qr(mat) # it factorizes the matrix
r

array([[-7.72771036,  1.16413712,  0.96571459,  1.29152649, -7.19962588],
       [ 0.        , -1.45315113,  0.27882796, -1.26045344, -2.704415  ],
       [ 0.        ,  0.        , -1.66365584, -0.23188213,  4.46121139],
       [ 0.        ,  0.        ,  0.        , -0.52749697,  1.18080989],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.57798627]])

### List of most common numpy linear algebra functions
[linear algebra](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html)

### List of most common random generation numbers functions
[Random generation functions](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.random.html)

### Use of If with Numpy ( Comparable to Excel If )

In [6]:
arr17 = np.random.randn(4,4)
arr17

array([[-0.80698012,  0.82146173,  0.85118693,  0.59274942],
       [-0.69264866, -1.51466877,  0.64512469,  0.93981984],
       [-0.91177793, -0.32712637,  0.89970265, -1.19422764],
       [ 1.27920864, -0.46153338, -0.37766538,  1.59690859]])

In [7]:
np.where(arr17 > 0, 2, -2) # typical if where if condition is met do x if not do y

array([[-2,  2,  2,  2],
       [-2, -2,  2,  2],
       [-2, -2,  2, -2],
       [ 2, -2, -2,  2]])

### Solving Systems of Linear Equations

We are going to solve equations of type:

$$
a \cdot x = b
$$

Consider the system of linear equations which fits the above type:

\begin{eqnarray}
a_1^1 \cdot x_1 + a_1^2 \cdot x_1 = b_1 \\
a_2^1 \cdot x_2 + a_2^2 \cdot x_2 = b_2
\end{eqnarray}

First, matrix $a$.

In [8]:
a = np.array([[3, 1], [1, 2]])

Second, vector $b$.

In [9]:
b = np.array([9, 8])

Third, the solution.

In [10]:
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [11]:
print (np.dot(a, x))  # checking
print ('Results matches vector b')

[9. 8.]
Results matches vector b


### Random Numbers

NumPy has powerful pseudo-random number generating functions available. Most of them get covered later. Very often, we use **standard-normally distributed pseudo-random numbers**.

In [12]:
np.random.standard_normal()  # single number

0.7659739990168295

In [13]:
np.random.standard_normal(5)  # 1d array

array([-1.19449899, -0.78789824, -0.95078651, -0.44543065, -0.23886733])

In [14]:
a = np.random.standard_normal((2, 6)) * 0.5  # 2d array
a

array([[ 0.14651342,  0.47945918,  0.29125753,  0.17798127, -0.19903907,
         0.6094033 ],
       [ 0.09394581, -0.7373813 ,  0.01795938,  0.3064833 , -0.29897585,
         0.4023563 ]])

In [15]:
np.round(a, 2)

array([[ 0.15,  0.48,  0.29,  0.18, -0.2 ,  0.61],
       [ 0.09, -0.74,  0.02,  0.31, -0.3 ,  0.4 ]])