In [5]:
import numpy as np

In [2]:
def descuento(r =0.10, periods = 10):
    arr = np.array([])
    for i in range(1,periods+1,1):
        factor = 1/((1+r)**i)
        arr = np.append(arr,factor)
    return arr

In [3]:
def crecimiento(r =0.10, periods = 10):
    arr = np.array([])
    for i in range(1,periods+1,1):
        factor = (1+r)**i
        arr = np.append(arr,factor)
    return arr

In [4]:
flujo = np.repeat(1000,10)

resultado = flujo * descuento()
resultado

array([909.09090909, 826.44628099, 751.3148009 , 683.01345537,
       620.92132306, 564.47393005, 513.15811823, 466.50738021,
       424.09761837, 385.54328943])

In [6]:
def factores(r,p):
    factor = 1/((1+r)**p)
    return factor

In [7]:
vec1 = [.1,.15,.20]
vec2 = range(1,len(vec1)+1)
arr1 = np.vectorize(factores)(vec1,vec2)

arr1

array([0.90909091, 0.75614367, 0.5787037 ])

In [14]:
import numpy as np

In [26]:
def disfactors(r,p):
    factor = p/((1+r)**(list(Discount_factors).index(r)+1))
    return factor

In [27]:
Discount_factors = [.10,.115,.12,.15,.18,.09]
Compounding_factors = [.08,.12,.06,.13,.05,.11]

In [28]:
np.vectorize(disfactors)(Discount_factors,np.repeat(1000,6))

array([909.09090909, 804.35962919, 711.78024781, 571.75324559,
       437.10921623, 596.26732688])

In [11]:
def compuesto(r,p):
    factor = ((1+r)**p)
    return factor

In [13]:
np.vectorize(compuesto)(Compounding_factors,np.repeat(1,6))

array([1.08, 1.12, 1.06, 1.13, 1.05, 1.11])